# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'CTMediatorDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "CTMediator"
  # Pods for CTMediatorDemo

  target 'CTMediatorDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CTMediatorDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
